package de.energiequant.xprc;

import java.time.Duration;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Optional;
import java.util.function.Consumer;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import de.energiequant.xprc.ConnectionParameters.DefaultPasswordProviders;

public class XPRCClientFactory {
    private static final Logger LOGGER = LoggerFactory.getLogger(XPRCClientFactory.class);

    private Consumer<XPRCException> exceptionHandler = new DefaultExceptionHandler();
    private final Collection<SessionMonitor> sessionMonitors = new ArrayList<>();

    private static final int MINIMUM_RECOMMENDED_CHANNEL_BLOCK_SECONDS = 30;
    private static final int MAXIMUM_RECOMMENDED_CHANNEL_BLOCK_SECONDS = 60;
    public static final Duration MINIMUM_RECOMMENDED_CHANNEL_BLOCK_DURATION = Duration.ofSeconds(MINIMUM_RECOMMENDED_CHANNEL_BLOCK_SECONDS);
    public static final Duration MAXIMUM_RECOMMENDED_CHANNEL_BLOCK_DURATION = Duration.ofSeconds(MAXIMUM_RECOMMENDED_CHANNEL_BLOCK_SECONDS);
    private Duration channelBlockDuration = MINIMUM_RECOMMENDED_CHANNEL_BLOCK_DURATION;

    /**
     * Configures the exception handler to be used for future clients.
     *
     * @param exceptionHandler will be called for exceptions during client operation
     * @return same instance for method-chaining
     */
    public XPRCClientFactory setExceptionHandler(Consumer<XPRCException> exceptionHandler) {
        this.exceptionHandler = exceptionHandler;
        return this;
    }

    /**
     * Adds a {@link SessionMonitor} to be registered with all clients/sessions created using this factory.
     *
     * @param sessionMonitor monitor to add
     * @return same instance for method-chaining
     */
    public XPRCClientFactory addSessionMonitor(SessionMonitor sessionMonitor) {
        sessionMonitors.add(sessionMonitor);
        return this;
    }

    /**
     * Configures how long channel IDs should remain blocked (not reusable) after having been released
     * (default: {@value #MINIMUM_RECOMMENDED_CHANNEL_BLOCK_SECONDS} seconds).
     * <p>
     * This is necessary because channel IDs are solely generated by clients but servers may require a short time
     * to catch up with properly terminating channels depending on maintenance intervals. The minimum time to wait
     * (if needed at all) depends on server implementation. XPRC protocol recommends to wait between
     * {@value #MINIMUM_RECOMMENDED_CHANNEL_BLOCK_SECONDS} and {@value #MAXIMUM_RECOMMENDED_CHANNEL_BLOCK_SECONDS}
     * seconds which should usually be sufficient considering that 14.7 million channels are available per session.
     * Commands will fail to be created if the channel is still regarded as blocked on server side.
     * </p>
     * <p>
     * {@link #MINIMUM_RECOMMENDED_CHANNEL_BLOCK_DURATION} and {@link #MAXIMUM_RECOMMENDED_CHANNEL_BLOCK_DURATION}
     * can be used to set protocol-recommended durations.
     * </p>
     * <p>
     * Note that block duration is also used to detect and mitigate concurrent channel termination for recently released
     * channels and thus should not be set too low.
     * </p>
     *
     * @param channelBlockDuration minimum time before released channel IDs are allowed to be reused
     * @return same instance for method-chaining
     */
    public XPRCClientFactory setChannelBlockDuration(Duration channelBlockDuration) {
        this.channelBlockDuration = channelBlockDuration;
        return this;
    }

    /**
     * Automatically selects the most recent local X-Plane installation having an XPRC plugin installed and creates
     * a client for it. Running instances are preferred but there is no guarantee that the found installation will
     * actually be running.
     *
     * <p>
     * See {@link #createAutoConfiguredClient(XPlaneInstance)} for additional details.
     * </p>
     *
     * @return XPRC client for most recent local X-Plane installation as determined at time of call
     * @see #createAutoConfiguredClient(XPlaneInstance)
     */
    public Optional<XPRCClient> createAutoConfiguredClient() {
        XPlaneInstance instance = XPlaneLocator.findMostRecentInstanceWithXPRC().orElse(null);
        if (instance == null) {
            LOGGER.debug("XPRC auto-configuration found no instance");
            return Optional.empty();
        }

        LOGGER.info("XPRC auto-configuration chooses X-Plane {} in {}", instance.getGeneration(), instance.getRootDirectory());
        return createAutoConfiguredClient(instance);
    }

    /**
     * Creates a client connecting to the given {@link XPlaneInstance} with {@link ConnectionParameters} automatically
     * being determined. Port will be statically configured at time of call, password will be read when needed (updated
     * automatically on reconnect if changed). Other parameters use default values.
     *
     * <p>
     * Automated configuration requires the installation's files to be accessible.
     * </p>
     *
     * <p>
     * You may want to use {@link #createClient(ConnectionParameters)} if you need more control or
     * {@link #createAutoConfiguredClient()} if you don't care about picking an {@link XPlaneInstance} on your own.
     * </p>
     *
     * @param xplaneInstance instance to create a client for
     * @return XPRC client automatically configured for the specified instance
     * @see #createAutoConfiguredClient()
     * @see #createClient(ConnectionParameters)
     */
    public Optional<XPRCClient> createAutoConfiguredClient(XPlaneInstance xplaneInstance) {
        if (xplaneInstance == null) {
            throw new IllegalArgumentException("X-Plane instance must not be null");
        }

        int port = xplaneInstance.readXPRCPort().orElse(-1);
        if (port < 1) {
            LOGGER.warn("Auto-configuration failed because XPRC port could not be read for X-Plane instance {}", xplaneInstance);
            return Optional.empty();
        }

        // fail early if password file cannot be read (probably a file permission problem)
        boolean canReadPassword = xplaneInstance.readXPRCPassword().isPresent();
        if (!canReadPassword) {
            LOGGER.warn("Auto-configuration failed because XPRC password could not be read for X-Plane instance {}", xplaneInstance);
            return Optional.empty();
        }

        return Optional.of(createClient(
            ConnectionParameters.builder()
                                .setPort(port)
                                .setPasswordProvider(DefaultPasswordProviders.readingXPRCPasswordFile(xplaneInstance))
                                .build()
        ));
    }

    /**
     * Creates a new client using the specified {@link ConnectionParameters}. The client will automatically be started
     * and attempt to connect.
     *
     * @param connectionParameters information required to (re)connect to an XPRC server
     * @return client configured according to factory settings and given {@link ConnectionParameters}
     */
    public XPRCClient createClient(ConnectionParameters connectionParameters) {
        return new XPRCClient(connectionParameters, exceptionHandler, sessionMonitors, channelBlockDuration);
    }
}
